services:
  cvetracker4rs:
    build:
      context: .
      dockerfile: Dockerfile
    image: cvetracker4rs:latest
    container_name: cvetracker4rs

    # Resource limits (Docker Compose syntax)
    cpus: 64.0 # 限制使用8个CPU核心
    mem_limit: 80g # 限制内存使用16GB

    # Volume mappings - 将容器内的结果映射到主机
    volumes:
      - ./analysis_results:/app/analysis_results # 分析结果目录
      - ./logs:/app/logs # 日志目录
      - ./logs_cg4rs:/app/logs_cg4rs # 日志目录
      - ./data/downloads:/data/downloads # 下载目录
      - ./data/working:/data/working # 工作目录
      - ./csv:/app/csv:ro # CSV文件（只读）

    # Environment variables
    environment:
      - RUST_LOG=info
      - DOWNLOAD_DIR=/data/downloads
      - WORKING_DIR=/data/working
      # PostgreSQL connection settings
      - PG_HOST=localhost:5432
      - PG_USER=${PG_USER:-postgres}
      - PG_PASSWORD=${PG_PASSWORD:-123}
      - PG_DATABASE=${PG_DATABASE:-crates_io}

    # Use host network to access host PostgreSQL
    network_mode: host

    # Alternative: use extra_hosts if you prefer bridge network
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # networks:
    #   - cvetracker-network

    # Restart policy
    restart: unless-stopped

    # Default command (can be overridden)
    command: [ "cvetracker4rs", "--help" ]
  # 使用独立的数据库容器，自动下载并导入 crates.io dump
  postgres:
    image: postgres:17
    container_name: cratesio-db
    user: "root"
    environment:
      POSTGRES_DB: ${PG_DATABASE:-crates_io}
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/cratesio_dump:/docker-entrypoint-initdb.d/dump
      - ./scripts/init-cratesio.sh:/docker-entrypoint-initdb.d/01-init-cratesio.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER:-postgres} -d ${PG_DATABASE:-crates_io}" ]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    network_mode: host
  # 使用host网络模式时不需要自定义网络
  # networks:
  #   cvetracker-network:
  #     driver: bridge

volumes:
  postgres_data:
